---
- name: k8s demo
  hosts: localhost
  gather_facts: false
  connection: local
  tasks:
    - name: create ido namespace
      kubernetes.core.k8s:
        api_version: v1
        kind: Namespace
        name: aap-demo
        state: present

    - name: create k8s pod
      kubernetes.core.k8s:
        src: deployment.yaml
        namespace: aap-demo
        state: present

- name: Create a VirtualMachine
  kubevirt.core.kubevirt_vm:
    state: present
    name: testvm
    namespace: default
    labels:
      app: test
    instancetype:
      name: u1.medium
    preference:
      name: fedora
    spec:
      domain:
        devices:
          interfaces:
          - name: default
            masquerade: {}
          - name: bridge-network
            bridge: {}
      networks:
      - name: default
        pod: {}
      - name: bridge-network
        multus:
          networkName: kindexgw
      volumes:
      - containerDisk:
          image: quay.io/containerdisks/fedora:latest
        name: containerdisk
      - cloudInitNoCloud:
          userData: |-
            #cloud-config
            # The default username is: fedora
            ssh_authorized_keys:
              - ssh-ed25519 AAAA...
        name: cloudinit
