---
- name: k8s demo
  hosts: localhost
  gather_facts: false
  connection: local
  vars:
  controller_validate_certs: false
collections:
  - community.kubevirt.kubevirt_vm 
  tasks:
    vars:
      controller_validate_certs: false
    collections:
      - 
    
    - name: create ido namespace
      kubernetes.core.k8s:
        api_version: v1
        kind: Namespace
        name: aap-demo
        state: present

    - name: create k8s pod
      kubernetes.core.k8s:
        src: deployment.yaml
        namespace: aap-demo
        state: present

#    - name: Start virtual machine 'myvm'
#      community.kubevirt.kubevirt_vm:
#          state: running
#          name: myvm
#          namespace: vms
