- name: k8s demo
  hosts: localhost
  gather_facts: false
  connection: local
  vars: null
  collections:
    - community.kubevirt.kubevirt_vm
  tasks:
    - name: create ido namespace
      kubernetes.core.k8s:
        api_version: v1
        kind: Namespace
        name: aap-demo
        state: present
    - name: create k8s pod
      kubernetes.core.k8s:
        src: deployment.yaml
        namespace: aap-demo
        state: present
    - name: Delete VM
      kubevirt.core.kubevirt_vm:
        name: testvm
        namespace: kubevirt-ansible
        state: absent
        wait: yes
