---
- hosts: all
- hosts: localhost

  collections:
  - kubernetes.core

  tasks:
  - name: Get a list of all pods from any namespace
    kubernetes.core.k8s_info:
      kind: Pod
      namespace: aap
    register: pod_list

- name: create k8s pod
    kubernetes.core.k8s:
      src: deployment.yaml
      namespace: ido
      state: present

- name: service create
    kubernetes.core.k8s:
      src: service.yaml
      namespace: ido
      state: present

- name: route create
    kubernetes.core.k8s:
      src: route.yaml
      namespace: ido
      state: present
