---
- hosts: all
- hosts: localhost

  collections:
  - kubernetes.core

  tasks:
  - name: create k8s pod
    kubernetes.core.k8s:
      src: deployment.yaml
      namespace: ido
      state: present
