---
- name: k8s demo
  hosts: localhost
  gather_facts: false
  connection: local
  tasks:
    - name: create ido namespace
      kubernetes.core.k8s:
        api_version: v1
        kind: Namespace
        name: idodo
        state: present

    - name: create k8s pod
      kubernetes.core.k8s:
        src: deployment.yaml
        namespace: idodo
        state: present
