---
- hosts: all
- hosts: localhost

  collections:
  - kubernetes.core

  tasks:
  - name: set ConfigMap example-config to present
    community.kubernetes.k8s:
      api_version: v1
      kind: ConfigMap
      name: example-config
      namespace: ido
      state: present
    ignore_errors: true 
