---
# tasks file for delete-namespace
    - name: create demo namespace
      redhat.openshift.k8s:
        name: ido-aap
        api_version: v1
        kind: Namespace
        state: present
    - name: Create foo config map
      redhat.openshift.k8s:
          definition:
              apiVersion: v1
              kind: ConfigMap
              metadata:
                  name: foo
                  namespace: default
              data:
                  color: “blue”
