---
# tasks file for delete-namespace
    - name: create namespace for kubevirt demo 
      redhat.openshift.k8s:
        name: test-aap
        api_version: v1
        kind: Namespace
        state: present
