---
# tasks file for create-namespace
    - name: create namespace for kubevirt demo 
      kubernetes.core.k8s:
        api_version: v1
        kind: Namespace
        name: kubevirt-ansible
        state: present
