---
  tasks:
    - name: Create cert-manager-operator namespace
      redhat.openshift.k8s:
        name: cert-manager-operator-ido
        api_version: v1
        kind: Namespace
        state: present
