- name: kubevirt collection for aap
  hosts: localhost
  gather_facts: false
  connection: local
  tasks:
    - name: create namespace for kubevirt demo 
      kubernetes.core.k8s:
        api_version: v1
        kind: Namespace
        name: kubevirt-ansible
        state: present

    - name: Create VM
      kubevirt.core.kubevirt_vm:
        state: present
        name: testvm
        namespace: kubevirt-ansible
        labels:
          app: test
        spec:
          domain:
            devices:
              interfaces:
              - name: default
                masquerade: {}
              - name: secondary-network
                bridge: {}
          networks:
          - name: default
            pod: {}
          - name: secondary-network
            multus:
              networkName: secondary-network
          accessCredentials:
          - sshPublicKey:
              source:
                secret:
                  secretName: my-pub-key
              propagationMethod:
                configDrive: {}
          volumes:
          - containerDisk:
              image: quay.io/containerdisks/fedora:latest
            name: containerdisk
          - cloudInitConfigDrive:
              userData: |-
                #cloud-config
                # The default username is: fedora
            name: cloudinit
        wait: yes
    - name: Delete VM
      kubevirt.core.kubevirt_vm:
        name: testvm
        namespace: kubevirt-ansible
        state: absent
        wait: yes
